name: Test Upgrade from PR to 6.0.0-alpha

on:
  pull_request:
    branches:
      - 5.2

permissions:
  contents: read
  actions: write

jobs:
  test-update:
    name: Test Update
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mautictest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql

    - name: Install dependencies
      run: |
        composer validate
        composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare testing environment
      run: |
        cp .github/ci-files/local.php config/local.php

    - name: Install from PR code
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        php bin/console mautic:install --force http://localhost

    - name: Download official 6.0.0-alpha update
      run: |
        curl -sSOL https://github.com/mautic/mautic/releases/download/6.0.0-alpha/6.0.0-alpha-update.zip
  
    - name: Modify update package with PR's CoreBundle/Update files
      run: |
        # Extract the official update zip
        unzip 6.0.0-alpha-update.zip -d mautic-update

        rm -rf mautic-update/vendor/symfony/cache/Adapter/DoctrineAdapter.php

        # Re-zip the modified update package
        cd mautic-update && zip -r ../6.0.0-alpha-update-modified.zip ./*
        cd ..
  
        # Replace original zip with modified one
        mv 6.0.0-alpha-update-modified.zip 6.0.0-alpha-update.zip
  
    - name: Apply modified update
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        php bin/console mautic:update:apply --force --update-package=6.0.0-alpha-update.zip

    - name: Delete file
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        rm -rf vendor/symfony/cache/Adapter/DoctrineAdapter.php

    - name: Delete cache
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        rm -rf var/cache/*

    - name: Apply modified update
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        php bin/console mautic:update:apply --continue